max_size = 5000000000
listen = "0.0.0.0:3000"
storage_nodes = ["http://0.0.0.0:3001"]
database_url = "http:/0.0.0.0.0:2003"
deduplicate = true
rebalance = false
rebalance_threshold = 0.0
persistence = false
log_file = "manager.log"
